---
title: "Projects"
---

The following is a collection of links to various projects I performed in the summer of 2020. These projects are based in R that I created by writing some code. Data Science is cool!

## [Lab 01 Building a project website](file:///Users/meaganbrown/Documents/github/meaganbrown.github.io/index.html)

In this assignment I learned:

- The steps needed in order to build a website 

- How to customize my website by writing code

- How to use the knit function in order to preview my website progress!

## [Lab 02 Analyzing Coronavirus Data ](file:///Users/meaganbrown/Documents/github/geog-176A-labs/docs/lab-02.html)
In this assignment I learned:

- Data wrangling and visualization skills

- How to hide my code and only display a chart or output on my html 

## [Lab 03 Distances and Projections ](https://meaganbrown.github.io/geog-176A-labs/lab-03.html)
In this assignment I learned:

- How to add labels to geometry points by using ggrepel

- How to drop units from a table

- How to manipulate geometries and coordinate systems


## [Lab 04 Tesselations, Point-in-Polygon  ](https://meaganbrown.github.io/geog-176A-labs/lab-04.html)

In this assignment I learned:

- The differences between different tesselating surfaces such as triangulation and hexagon

- How to use point-in-polygon counts to aggregate point data

- How to simplify data so that we aren't working with as many geometries and can run code faster

## [Lab 05 Rasters and Remote Sensing  ](https://meaganbrown.github.io/geog-176A-labs/lab-05.html)

In this assignment I learned:

- How to work with multiband raster files to detect and analyze a flood event

- How different stretches such as "hist" and "lin" effect how we analyze different data on maps

- How to create a raster stack

## [Lab 06 Terrain Analysis ](https://meaganbrown.github.io/geog-176A-labs/lab-05.html)

In this assignment I learned:

- How to prepare terrain for analysis 

- How to perform multi-data structure(raster/vector) analysis

- How to retrieve field data 
